# Generated by Django 5.1.3 on 2024-11-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="sent_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="room_to_sent",
                to="chat.room",
            ),
        ),
    ]
